language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

notifications:
  email:
    on_failure: change # [always|never|change] default: always

# no dependencies (coveralls, ipython only needed for testing)
install:
  - pip install coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install ipython==1.0; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install ipython; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install ipython; fi

script: nosetests --with-doctest --with-coverage --cover-package=param

after_success: coveralls
