sudo: false
language: python

stages:
  - test
  - deploy

jobs:
  include:
    - &tests
      stage: test
      python: 2.7
      env: TOX_ENV=py27
      install:
        - pip install tox
      script:
        - tox -e $TOX_ENV

    - <<: *tests
      python: 3.6
      env: TOX_ENV=py36

    - stage: deploy
      python: 3.6
      install:
        - python -v
      script:
        - python -v

    - stage: deploy
      install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda config --set always_yes yes --set changeps1 no
        - conda update conda
        - conda install conda-build=3.0.25
        - conda install anaconda-client
      script:
        - python -v
        - conda build conda.recipe
