sudo: false
language: python

stages:
  - lint
  - test
  - deploy to anaconda
  - deploy to pypi

jobs:
  include:
    - &tests
      stage: test
      python: 3.6
      env: TOX_ENV=py36
      install:
        - pip install tox
      script:
        - tox -e $TOX_ENV

    - <<: *tests
      stage: lint
      env: TOX_ENV=flake8

    - <<: *tests
      python: 3.5
      env: TOX_ENV=py35

    - <<: *tests
      python: 3.4
      env: TOX_ENV=py34

    - <<: *tests
      python: 3.3
      env: TOX_ENV=py33

    - <<: *tests
      python: 3.2
      env: TOX_ENV=py32

    - <<: *tests
      python: pypy
      env: TOX_ENV=pypy

    - <<: *tests
      python: 2.7
      env: TOX_ENV=py27

    - <<: *tests
      python: 2.6
      env: TOX_ENV=py26

    - stage: deploy to pypi
      python: 3.6
      install:
        - python --version
      script:
        - python --version

    - stage: deploy to anaconda
      install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda config --set always_yes yes --set changeps1 no
        - conda update conda
        - conda install conda-build anaconda-client
      script:
        - conda build conda.recipe
