# things not included
# language
# notifications - no email notifications set up

name: pytest
on:
  pull_request:
    branches:
    - '*'

jobs:
  test_suite:
    name: Tox on ${{ matrix.python-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9]
    timeout-minutes: 30
    defaults:
      run:
        shell: bash -l {0} 
    env:
      PYTHON_VERSION: ${{ matrix.python-version }}
      CHANS_DEV: "-c pyviz/label/dev"
      CHANS: "-c pyviz"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "100"
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: set tox-env
        run: |
          pyver="{{ matrix.python-version }}"
          echo "::set-env name=TOX_ENV::${pyver//.}"
      - name: Fetch
        run: git fetch --prune --tags
      - name: env setup
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: doit test_lint
        run: |
          flake8
      - name: doit test_unit
        run: |
          tox -e $TOX_ENV
